### ISSUE TITLE
d3 is not defined when rendering legend in test

### ISSUE THREAD

**Issue by mattpage** [jivesoftware/react-d3-charts#3]
ReferenceError: d3 is not defined
      at Object.module.exports [as color](node_modules/d3-svg-legend/src/color.js:5:15)
      at [object Object].renderLegend (node_modules/react-d3-charts/lib/Chart.js:99:53)
      at [object Object].componentDidMount (node_modules/react-d3-charts/lib/Chart.js:25:10)

**Comment by mattpage** [comment]
[d3-legend](https://github.com/susielu/d3-legend) is used to create legends.
It has d3 as a peer dependency, but it doesn't work quite right in test environments.
I was able to work around this by globally defining d3 in my test before including the chart.

```
global.d3 = require('d3');
```
